### PR TITLE
Add DevExtreme React Chart

### PR DESCRIPTION
**Pull request by Krijovnick**
I'm add the link to the DevExtreme React Chart.

### CODE REVIEW

**Comment by hslatman** [comment]
Do you have some information about the performance of React Chart with large amounts or fast data?

**Comment by Krijovnick** [comment]
The React Chart is in the beta version now and we cannot for now share the time it requires to draw itself. We will prepare this data by the release time.

**Comment by koconder** [comment]
@hslatman please provide information on volume of users/downloads and performance. As its not on Github its hard to gauge interest/usage in that package

**Comment by hslatman** [comment]
I think you meant to say @Krijovnick, @koconder 🙂

**Comment by Krijovnick** [comment]
Hello, @koconder and @hslatman
In the [example](https://codesandbox.io/s/mz7kkq7oj8) you can see how much time is required to draw a React Chart with a different amount of data. You can try changing the number of data points and check the performance.
DevExtreme React Chart is available on the [npm](https://www.npmjs.com/package/@devexpress/dx-react-chart) and [github](https://github.com/DevExpress/devextreme-reactive), where you can find information about the volume of users and downloads.

**Comment by koconder** [comment]
@Krijovnick added!

**Pull request merged**
