### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vagelim**
added monitoring guides for Kafka and Hadoop

### CODE REVIEW

**Comment by vagelim** [comment]
Hey @onurakpolat, any comment as to why this was closed? Was the PR description not descriptive enough or...?

**Comment by onurakpolat** [comment]
Hej @vagelim, I appreciate your contribution however I don't want this list to become a marketing channel. The idea is to keep the section limited to independent content rather than companies content marketing.

**Comment by vagelim** [comment]
The Kafka series was produced with the help of Gwen Shapira (one of the core developers of Kafka), and I have been told by employees of Confluent that they've passed it around internally to their own engineers. So while I understand your concern, I respectfully submit that only the last part of the series (part 3) is actually content marketing. It's the only piece of either documents that mentions Datadog at all. The rest stand on their own.

**Comment by vagelim** [comment]
If your issue is with the content being hosted on datadoghq.com, we also have the full blog posts available as markdown links:
https://github.com/DataDog/the-monitor/blob/master/kafka/monitoring-kafka-performance-metrics.md
https://github.com/DataDog/the-monitor/blob/master/hadoop/how_to_monitor_hadoop_metrics.md

Though if you feel the content is "content marketing", then it probably makes no difference where the content is hosted.

**Comment by onurakpolat** [comment]
@vagelim thanks for providing more context. It makes sense, apologies for my initial resistance.

**Comment by vagelim** [comment]
@onurakpolat Thanks for taking the time to explain the issue to me. I totally understand wanting to keep this useful list free of commercial influence! I just wanted to spread these two guides in particular because of the community feedback I've received around their utility. :)

**Pull request merged**
